// Stub for src/main/main.js -- GENERATED from actual usage.
//
// Every name any source file imports from main/main is exported here. It was
// generated by RESOLVING import paths (./main, ../main/main, main/main all
// name the same module) rather than pattern-matching the specifier text --
// the first attempt matched only 'main/main' and missed 9 names reached via
// relative paths, which surfaced as a crash per missing export.
//
// `player` and `characterSelections` are the live arrays the tests mutate.

export function addMatchTimer() {}
export function addPlayer() {}
export function addShine() {}
export const bg1 = 0;
export const bg2 = 0;
export const calibrationPlayer = 0;
export function changeGamemode() {}
export const characterSelections = [];
export function clearScreen() {}
export const controllerResetCountdowns = [];
export const cpuDifficulty = [];
export const currentPlayers = [];
export const edgeOffset = [];
export const endGame = 0;
export const fg1 = 0;
export const fg2 = 0;
export const findPlayers = 0;
export function finishGame() {}
export const gameEnd = 0;
export const gameMode = 0;
export function getCookie() {}
export function getStartTimer() {}
export function hasTag() {}
export const holiday = 0;
export function initializePlayers() {}
export const keyBind = [];
export const keyBinding = [];
export const keys = [];
export const layers = [];
export const mType = 0;
export const matchTimer = 0;
export const pPal = [];
export const palettes = [];
export const pause = false;
export const percentShake = [];
export const player = [];
export const playerType = [];
export const playing = false;
export const ports = [];
export function positionPlayersInCSS() {}
export const randomTags = [];
export const screenShake = 0;
export function setCS() {}
export function setCalibrationPlayer() {}
export function setControllerReset() {}
export function setCookie() {}
export function setCreditsPlayer() {}
export function setCurrentPlayer() {}
export function setEndTargetGame() {}
export function setFindingPlayers() {}
export function setKeyBinding() {}
export function setMatchTimer() {}
export function setMtype() {}
export function setPlayerType() {}
export function setPlaying() {}
export function setShine() {}
export function setStage() {}
export function setStageSelect() {}
export function setStartTimer() {}
export function setStarting() {}
export function setTagText() {}
export function setUsingCustomControls() {}
export function setVersusMode() {}
export const shine = 0;
export const showDebug = false;
export const snowCount = 0;
export const stageSelect = 0;
export function startGame() {}
export function startTimer() {}
export function starting() {}
export const tagText = [];
export function togglePort() {}
export const ui = false;
export const versusMode = 0;
